spring:
  datasource:
    #data: classpath:/contacts-500k.sql
    data: classpath:/data.sql

# PostgreSQL settings section    
# ---------------------------
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 60000
#      maximum-pool-size: 5
#    initialization-mode: always
#    password: changeme
#    platform: postgres
#    username: postgres
#    url: jdbc:postgresql://192.168.88.6:5432/sipsoft
#    #url: jdbc:postgresql://localhost:5432/sipsoft
#    #url: jdbc:postgresql://192.168.123.6:5432/sipsoft
# ----------------------------    
    
    
# H2 settings section    
# -------------------
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: test
    password: test
  
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
# -------------------     

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      
  mvc:
    async:
      request-timeout: 3600000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: TRACE
    depavlo: DEBUG
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %highlight(%-5level) %green(%C{1.}):[%L - %msg%n%throwable'

    